### ISSUE TITLE
Error when attempting to run gatsby with `gatsby-source-github-contributors`

### ISSUE THREAD

**Issue by brekk** [patrick91/gatsby-source-github-contributors#1]
`The "data" argument must be one of type string, Buffer, TypedArray, or DataView. Received type number`

<details>

```
"gatsby-source-github-contributors" threw an error while running the sourceNodes lifecycle:

The "data" argument must be one of type string, Buffer, TypedArray, or DataView. Received type number

  30 |             internal: {
  31 |                 type: "GitHubContributor",
> 32 |                 contentDigest: createContentDigest(node.id)
     |                                ^
  33 |             }
  34 |         });
  35 |     });
```

</details>

However, I was able to fix the issue by simply coercing the node.id into a string:

```
contentDigest: createContentDigest('' + node.id)
```

I'd be happy to submit a PR for this if you want -- I'd also like to maybe push some error handling, as this module fails but doesn't block the build, and it probably should(?)

**Comment by brekk** [comment]
PR here: https://github.com/patrick91/gatsby-source-github-contributors/pull/2

**Comment by brekk** [comment]
@patrick91 🙏🏽 Thanks for merging the PR! Would you be able to push a new version sometime soon? (No rush but I've had to shim this plugin for my site in the interim time)

**Comment by patrick91** [comment]
@brekk should be done now! thanks a lot. I'll close this, let me know if something went wrong :)

**Comment by brekk** [comment]
Works perfectly after upgrading, thanks!
